// height_block (높이 블록 (지그와 한 벌, 따로 출력)) -- generated by make_tools.py from /private/tmp/claude-501/-Users-kwg-Desktop-mydrive-project-Toccata/2f19e142-4ac2-4c90-bd1e-b3b469f97487/scratchpad/v4/final; USE coordinates mapped to the print bed
$fn=48;
multmatrix([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, -5.0], [0, 0, 0, 1]]) union(){
 difference(){
  union(){
   multmatrix([[0,0,1,0.0000],[1,0,0,0],[0,1,0,0],[0,0,0,1]]) linear_extrude(height=10.0000) polygon(points=[[15.9900,5.0000],[18.0100,5.0000],[18.0100,42.0000],[15.9900,42.0000]]);
   multmatrix([[0,0,1,0.0000],[1,0,0,0],[0,1,0,0],[0,0,0,1]]) linear_extrude(height=10.0000) polygon(points=[[0.0000,5.0000],[8.0000,5.0000],[8.0000,43.6500],[0.0000,43.6500]]);
   multmatrix([[0,0,1,0.0000],[1,0,0,0],[0,1,0,0],[0,0,0,1]]) linear_extrude(height=10.0000) polygon(points=[[8.0000,5.0000],[16.0000,5.0000],[16.0000,43.3500],[8.0000,43.3500]]);
   multmatrix([[0,0,1,0.0000],[1,0,0,0],[0,1,0,0],[0,0,0,1]]) linear_extrude(height=10.0000) polygon(points=[[18.0000,5.0000],[26.0000,5.0000],[26.0000,55.6500],[18.0000,55.6500]]);
   multmatrix([[0,0,1,0.0000],[1,0,0,0],[0,1,0,0],[0,0,0,1]]) linear_extrude(height=10.0000) polygon(points=[[26.0000,5.0000],[34.0000,5.0000],[34.0000,55.3500],[26.0000,55.3500]]);
  }
  multmatrix([[0, 0, 1, 9.6], [1, 0, 0, 4.0], [0, 1, 0, 39.65], [0, 0, 0, 1]]) linear_extrude(height=0.410) text("W+", size=3.40, font="Arial:style=Bold", halign="center", valign="center");
  multmatrix([[0, 0, 1, 9.6], [1, 0, 0, 12.0], [0, 1, 0, 39.35], [0, 0, 0, 1]]) linear_extrude(height=0.410) text("W-", size=3.40, font="Arial:style=Bold", halign="center", valign="center");
  multmatrix([[0, 0, 1, 9.6], [1, 0, 0, 22.0], [0, 1, 0, 51.65], [0, 0, 0, 1]]) linear_extrude(height=0.410) text("B+", size=3.40, font="Arial:style=Bold", halign="center", valign="center");
  multmatrix([[0, 0, 1, 9.6], [1, 0, 0, 30.0], [0, 1, 0, 51.35], [0, 0, 0, 1]]) linear_extrude(height=0.410) text("B-", size=3.40, font="Arial:style=Bold", halign="center", valign="center");
  multmatrix([[0, 0, 1, 9.6], [1, 0, 0, 8.0], [0, 1, 0, 12.0], [0, 0, 0, 1]]) linear_extrude(height=0.410) text("W 43.5", size=2.80, font="Arial:style=Bold", halign="center", valign="center");
  multmatrix([[0, 0, 1, 9.6], [1, 0, 0, 26.0], [0, 1, 0, 12.0], [0, 0, 0, 1]]) linear_extrude(height=0.410) text("B 55.5", size=2.80, font="Arial:style=Bold", halign="center", valign="center");
 }
 
}
