// Toccata stage-0 C01c - 패드 받침판 (2개: 후보 재료마다 1개) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
union(){
translate([0.0000,0.0000,0.0000]) cube([20.0000,11.0000,4.0000]);
translate([26.0000,0.0000,0.0000]) cube([20.0000,11.0000,4.0000]);
}
translate([4.0000,2.5000,3.7000]) cube([12.0000,6.0000,1.3000]);
translate([30.0000,2.5000,3.7000]) cube([12.0000,6.0000,1.3000]);
}
