// Toccata stage-0 C01d - 봉 끝 칼라 (2개) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
translate([0.0000,0.0000,0.0000]) cylinder(h=3.0000, d=9.0000, $fn=64);
translate([0.0000,0.0000,-1.0000]) cylinder(h=5.0000, d=3.9000, $fn=64);
}
difference(){
translate([12.0000,0.0000,0.0000]) cylinder(h=3.0000, d=9.0000, $fn=64);
translate([12.0000,0.0000,-1.0000]) cylinder(h=5.0000, d=3.9000, $fn=64);
}
