// Toccata stage-0 C02a - 패드 압축 지그 (바탕·안내 통) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
union(){
difference(){
union(){
translate([0.0000,0.0000,0.0000]) cube([60.0000,60.0000,4.0000]);
translate([20.4000,16.4000,3.9900]) cube([19.2000,27.2000,22.0100]);
}
translate([22.8000,18.8000,4.0000]) cube([14.4000,22.4000,36.0000]);
}
translate([24.0000,20.0000,3.9900]) cube([12.0000,20.0000,2.0100]);
}
translate([26.8000,23.8000,5.0000]) cube([6.4000,12.4000,5.0000]);
translate([30.0000,7.0000,3.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("C02 pad", size=4.000, font="Liberation Sans:style=Bold", halign="center", valign="center");
}
