// Toccata stage-0 C02b - 패드 압축 누름 막대 (추 받침판 80×80) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
union(){
translate([0.0000,0.0000,0.0000]) cube([80.0000,80.0000,3.0000]);
translate([33.0000,29.0000,2.9900]) cube([14.0000,22.0000,24.0100]);
}
translate([8.0000,8.0000,-1.0000]) cylinder(h=6.0000, d=4.2000, $fn=64);
translate([60.0000,12.0000,2.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("C02b", size=4.000, font="Liberation Sans:style=Bold", halign="center", valign="center");
}
