// Toccata stage-0 C03a - 윗판 굽힘 띠 (3개) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
translate([0.0000,0.0000,0.0000]) cube([120.0000,12.0000,5.5000]);
translate([8.0000,6.0000,4.9000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("C03a-1 t5.5", size=3.000, font="Liberation Sans:style=Bold", halign="left", valign="center");
}
difference(){
translate([0.0000,16.0000,0.0000]) cube([120.0000,12.0000,5.5000]);
translate([8.0000,22.0000,4.9000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("C03a-2 t5.5", size=3.000, font="Liberation Sans:style=Bold", halign="left", valign="center");
}
difference(){
translate([0.0000,32.0000,0.0000]) cube([120.0000,12.0000,5.5000]);
translate([8.0000,38.0000,4.9000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("C03a-3 t5.5", size=3.000, font="Liberation Sans:style=Bold", halign="left", valign="center");
}
