// Toccata stage-0 C03b - 3점 굽힘 받침 (R2 두 날, 간격 100) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
union(){
translate([0.0000,0.0000,0.0000]) cube([30.0000,120.0000,4.0000]);
hull(){translate([0,10.000,12]) rotate([0,90,0]) cylinder(h=30, r=2.0, $fn=48); translate([0,5.000,0]) cube([30,10,1]);}
hull(){translate([0,110.000,12]) rotate([0,90,0]) cylinder(h=30, r=2.0, $fn=48); translate([0,105.000,0]) cube([30,10,1]);}
}
translate([15.0000,60.0000,3.4000]) rotate([0,0,90.00]) linear_extrude(height=0.8000) text("C03b span 100", size=3.500, font="Liberation Sans:style=Bold", halign="center", valign="center");
}
