// Toccata stage-0 C03c - 누름 코 (R2 날 + 손가락 받침 24×24, 가운데 Ø4 다이얼 구멍) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
union(){
translate([0.0000,0.0000,0.0000]) cube([24.0000,24.0000,3.0000]);
hull(){translate([0,12,11]) rotate([0,90,0]) cylinder(h=24, r=2.0, $fn=48); translate([0,7,2.99]) cube([24,10,1]);}
}
translate([12.0000,12.0000,-1.0000]) cylinder(h=21.0000, d=4.0000, $fn=64);
}
