// Toccata stage-0 C03d - 다이얼 게이지 스탠드, 낮은 (굽힘 띠용) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
translate([0,0,0.0000]) linear_extrude(height=16.0000) polygon([[0.0000,0.0000],[60.0000,0.0000],[60.0000,6.0000],[14.0000,6.0000],[14.0000,45.0000],[58.0000,45.0000],[58.0000,57.0000],[2.0000,57.0000],[2.0000,6.0000],[0.0000,6.0000]]);
translate([46,44.000,6]) rotate([-90,0,0]) linear_extrude(height=14) union(){circle(d=8.1500, $fn=48); rotate(225.000) square([4.0750,4.0750]);}
translate([45.5000,44.0000,6.0000]) cube([1.0000,14.0000,11.0000]);
translate([46.6,51.000,12.6]) rotate([0,90,0]) cylinder(h=12, d=3.3, $fn=32);
translate([36,51.000,12.6]) rotate([0,90,0]) cylinder(h=10, d=2.7, $fn=32);
translate([8.0000,3.0000,15.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("C03d", size=3.200, font="Liberation Sans:style=Bold", halign="center", valign="center");
}
