// Toccata stage-0 C04c - 봉 받침 (당김 시험용, 저울 위) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
union(){
translate([0.0000,0.0000,0.0000]) cube([90.0000,60.0000,3.0000]);
translate([34.0190,22.0000,2.9900]) cube([3.0000,16.0000,26.0100]);
translate([52.9810,22.0000,2.9900]) cube([3.0000,16.0000,26.0100]);
}
translate([-1,30,23.000]) rotate([90,0,90]) linear_extrude(height=92) union(){circle(d=4.0500, $fn=48); rotate(45.000) square([2.0250,2.0250]);}
translate([20.0000,10.0000,2.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("C04c rod", size=4.000, font="Liberation Sans:style=Bold", halign="center", valign="center");
}
