// Toccata stage-0 C05a - 가이드 탭 날 (프레임 쪽, 흑 6.8·6.9·7.0 / 백 7.4·7.5·7.6) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
union(){
translate([0.0000,0.0000,0.0000]) cube([66.0000,22.0000,3.0000]);
translate([4.0000,6.0000,2.9900]) cube([6.8000,10.0000,12.0100]);
translate([14.3000,6.0000,2.9900]) cube([6.9000,10.0000,12.0100]);
translate([24.7000,6.0000,2.9900]) cube([7.0000,10.0000,12.0100]);
translate([35.2000,6.0000,2.9900]) cube([7.4000,10.0000,12.0100]);
translate([46.1000,6.0000,2.9900]) cube([7.5000,10.0000,12.0100]);
translate([57.1000,6.0000,2.9900]) cube([7.6000,10.0000,12.0100]);
}
translate([7.4000,3.0000,2.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("6.8", size=2.200, font="Liberation Sans:style=Bold", halign="center", valign="center");
translate([17.7500,3.0000,2.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("6.9", size=2.200, font="Liberation Sans:style=Bold", halign="center", valign="center");
translate([28.2000,3.0000,2.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("7.0", size=2.200, font="Liberation Sans:style=Bold", halign="center", valign="center");
translate([38.9000,3.0000,2.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("7.4", size=2.200, font="Liberation Sans:style=Bold", halign="center", valign="center");
translate([49.8500,3.0000,2.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("7.5", size=2.200, font="Liberation Sans:style=Bold", halign="center", valign="center");
translate([60.9000,3.0000,2.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("7.6", size=2.200, font="Liberation Sans:style=Bold", halign="center", valign="center");
}
