// Toccata stage-0 C05b - 건반 홈 쿠폰 (흑 벽 사이 8.0, 백 갈비 사이 8.6) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
union(){
translate([0.0000,0.0000,0.0000]) cube([10.4000,14.0000,2.0000]);
translate([0.0000,0.0000,1.9900]) cube([1.2000,14.0000,12.0100]);
translate([9.2000,0.0000,1.9900]) cube([1.2000,14.0000,12.0100]);
}
translate([5.2000,7.0000,1.4000]) rotate([0,0,90.00]) linear_extrude(height=0.8000) text("B8.0", size=2.400, font="Liberation Sans:style=Bold", halign="center", valign="center");
}
difference(){
union(){
translate([22.0000,0.0000,0.0000]) cube([11.0000,14.0000,2.0000]);
translate([22.0000,0.0000,1.9900]) cube([1.2000,14.0000,12.0100]);
translate([31.8000,0.0000,1.9900]) cube([1.2000,14.0000,12.0100]);
}
translate([27.5000,7.0000,1.4000]) rotate([0,0,90.00]) linear_extrude(height=0.8000) text("W8.6", size=2.400, font="Liberation Sans:style=Bold", halign="center", valign="center");
}
