// Toccata stage-0 C07a - 밸런스 핀 압입 레일 쿠폰 (구멍 Ø1.80~2.00, 5개) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
translate([0.0000,0.0000,0.0000]) cube([70.0000,12.2000,14.0000]);
translate([8.0000,7.6000,-1.0000]) cylinder(h=16.0000, d=1.8000, $fn=48);
translate([8.0000,2.6000,13.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("1.80", size=2.300, font="Liberation Sans:style=Bold", halign="center", valign="center");
translate([21.5000,7.6000,-1.0000]) cylinder(h=16.0000, d=1.8500, $fn=48);
translate([21.5000,2.6000,13.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("1.85", size=2.300, font="Liberation Sans:style=Bold", halign="center", valign="center");
translate([35.0000,7.6000,-1.0000]) cylinder(h=16.0000, d=1.9000, $fn=48);
translate([35.0000,2.6000,13.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("1.90", size=2.300, font="Liberation Sans:style=Bold", halign="center", valign="center");
translate([48.5000,7.6000,-1.0000]) cylinder(h=16.0000, d=1.9500, $fn=48);
translate([48.5000,2.6000,13.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("1.95", size=2.300, font="Liberation Sans:style=Bold", halign="center", valign="center");
translate([62.0000,7.6000,-1.0000]) cylinder(h=16.0000, d=2.0000, $fn=48);
translate([62.0000,2.6000,13.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("2.00", size=2.300, font="Liberation Sans:style=Bold", halign="center", valign="center");
}
