// Toccata stage-0 C07b - 핀 돌출 게이지 (4.30) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
translate([0.0000,0.0000,0.0000]) cube([30.0000,10.0000,8.0000]);
translate([15.0000,5.0000,-1.0000]) cylinder(h=5.3000, d=2.4000, $fn=32);
translate([15.0000,5.0000,7.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("4.30", size=3.500, font="Liberation Sans:style=Bold", halign="center", valign="center");
}
