// Toccata stage-0 C08a - 캡스턴 너트 트랩 빔 쿠폰 (5종) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
union(){
translate([0.0000,0.0000,0.0000]) cube([86.0000,26.0000,3.0000]);
translate([6.0000,3.0000,2.9900]) cube([8.0000,20.0000,5.7100]);
translate([22.0000,3.0000,2.9900]) cube([8.0000,20.0000,5.7100]);
translate([38.0000,3.0000,2.9900]) cube([8.0000,20.0000,5.7100]);
translate([54.0000,3.0000,2.9900]) cube([8.0000,20.0000,5.7100]);
translate([70.0000,3.0000,2.9900]) cube([8.0000,20.0000,5.7100]);
}
translate([10.0000,13.0000,-1.0000]) cylinder(h=4.0100, d=7.0000, $fn=64);
translate([10.0000,13.0000,6.6900]) cylinder(h=3.0100, d=3.3000, $fn=64);
translate([10.0000,13.0000,2.9900]) cylinder(h=1.1200, d=2.8000, $fn=32);
translate([7.2000,10.2000,4.1000]) cube([7.8000,5.6000,2.6000]);
translate([10.0000,24.6000,2.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("1", size=2.200, font="Liberation Sans:style=Bold", halign="center", valign="center");
translate([26.0000,13.0000,-1.0000]) cylinder(h=4.0100, d=7.0000, $fn=64);
translate([26.0000,13.0000,6.6900]) cylinder(h=3.0100, d=3.3000, $fn=64);
translate([26.0000,13.0000,2.9900]) cylinder(h=1.1200, d=2.8000, $fn=32);
translate([23.1500,10.1500,4.1000]) cube([7.8500,5.7000,2.6000]);
translate([26.0000,24.6000,2.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("2", size=2.200, font="Liberation Sans:style=Bold", halign="center", valign="center");
translate([42.0000,13.0000,-1.0000]) cylinder(h=4.0100, d=7.0000, $fn=64);
translate([42.0000,13.0000,6.6900]) cylinder(h=3.0100, d=3.3000, $fn=64);
translate([42.0000,13.0000,2.9900]) cylinder(h=1.1200, d=2.8000, $fn=32);
translate([39.1000,10.1000,4.1000]) cube([7.9000,5.8000,2.6000]);
translate([42.0000,24.6000,2.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("3", size=2.200, font="Liberation Sans:style=Bold", halign="center", valign="center");
translate([58.0000,13.0000,-1.0000]) cylinder(h=4.0100, d=7.0000, $fn=64);
translate([58.0000,13.0000,6.6900]) cylinder(h=3.0100, d=3.3000, $fn=64);
translate([58.0000,13.0000,2.9900]) cylinder(h=1.1200, d=2.7000, $fn=32);
translate([55.2000,10.2000,4.1000]) cube([7.8000,5.6000,2.6000]);
translate([58.0000,24.6000,2.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("4", size=2.200, font="Liberation Sans:style=Bold", halign="center", valign="center");
translate([74.0000,13.0000,-1.0000]) cylinder(h=4.0100, d=7.0000, $fn=64);
translate([74.0000,13.0000,6.6900]) cylinder(h=3.0100, d=3.3000, $fn=64);
translate([74.0000,13.0000,2.9900]) cylinder(h=1.1200, d=2.9000, $fn=32);
translate([71.2000,10.2000,4.1000]) cube([7.8000,5.6000,2.6000]);
translate([74.0000,24.6000,2.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("5", size=2.200, font="Liberation Sans:style=Bold", halign="center", valign="center");
}
