// Toccata stage-0 C09a - 두께 측정 받침 (22×22 자리 + 깊이 막대 다리) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
union(){
translate([0.0000,0.0000,0.0000]) cube([34.0000,70.0000,4.0000]);
translate([6.0000,13.0000,3.9900]) cube([22.0000,22.0000,1.0100]);
translate([0.0000,50.0000,3.9900]) cube([4.0000,10.0000,23.0100]);
translate([30.0000,50.0000,3.9900]) cube([4.0000,10.0000,23.0100]);
translate([0.0000,50.0000,24.0000]) cube([34.0000,10.0000,3.0000]);
}
translate([17.0000,55.0000,23.0000]) cylinder(h=5.0000, d=4.0000, $fn=64);
translate([17.0000,6.0000,3.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("C09a", size=4.000, font="Liberation Sans:style=Bold", halign="center", valign="center");
}
