// Toccata stage-0 C09b - 누름판 (발 20×20, 강철 블록 자리) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
union(){
translate([0.0000,0.0000,0.0000]) cube([24.0000,60.0000,4.0000]);
translate([2.0000,10.0000,3.9900]) cube([20.0000,20.0000,2.0100]);
}
translate([7.2500,0.0000,-1.0000]) cube([9.5000,40.5000,2.5000]);
}
