// Toccata stage-0 C10a - 패드 바 잎 혀 쿠폰 (3개) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
union(){
translate([0.0000,0.0000,0.0000]) cube([10.0000,10.0000,1.5000]);
translate([4.2000,9.9900,0.0000]) cube([1.6000,8.0100,0.6000]);
translate([4.2000,17.2000,0.5900]) cube([1.6000,0.8000,0.6100]);
}
translate([5.0000,5.0000,0.9000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("1", size=3.000, font="Liberation Sans:style=Bold", halign="center", valign="center");
}
difference(){
union(){
translate([14.0000,0.0000,0.0000]) cube([10.0000,10.0000,1.5000]);
translate([18.2000,9.9900,0.0000]) cube([1.6000,8.0100,0.6000]);
translate([18.2000,17.2000,0.5900]) cube([1.6000,0.8000,0.6100]);
}
translate([19.0000,5.0000,0.9000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("2", size=3.000, font="Liberation Sans:style=Bold", halign="center", valign="center");
}
difference(){
union(){
translate([28.0000,0.0000,0.0000]) cube([10.0000,10.0000,1.5000]);
translate([32.2000,9.9900,0.0000]) cube([1.6000,8.0100,0.6000]);
translate([32.2000,17.2000,0.5900]) cube([1.6000,0.8000,0.6100]);
}
translate([33.0000,5.0000,0.9000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("3", size=3.000, font="Liberation Sans:style=Bold", halign="center", valign="center");
}
