// Toccata stage-0 C10b - 잎 크리프 받침 (0.3 / 0.6 눌림 두 자리) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
union(){
translate([0.0000,0.0000,0.0000]) cube([48.0000,26.0000,2.0000]);
translate([3.0000,2.0000,1.9900]) cube([12.0000,11.0000,2.0100]);
translate([5.0000,19.7000,1.9900]) cube([8.0000,2.8000,1.7100]);
translate([26.0000,2.0000,1.9900]) cube([12.0000,11.0000,2.0100]);
translate([28.0000,19.7000,1.9900]) cube([8.0000,2.8000,2.0100]);
}
translate([9.0000,7.5000,3.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("0.3", size=3.000, font="Liberation Sans:style=Bold", halign="center", valign="center");
translate([32.0000,7.5000,3.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("0.6", size=3.000, font="Liberation Sans:style=Bold", halign="center", valign="center");
}
