// Toccata stage-0 C10c - 잎 힘 측정 받침 (뿌리 물림 턱 높이 12) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
union(){
translate([0.0000,0.0000,0.0000]) cube([30.0000,24.0000,3.0000]);
translate([0.0000,0.0000,2.9900]) cube([30.0000,12.0000,9.0100]);
}
translate([15.0000,18.0000,2.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("C10c", size=4.000, font="Liberation Sans:style=Bold", halign="center", valign="center");
}
