// Toccata stage-0 C12a - 층간 인장 쿠폰 (핀 두께 1.8 × 폭 2.0, 3개) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
union(){
translate([0.0000,0.0000,0.0000]) cube([16.0000,8.0000,10.0000]);
hull(){translate([0.0000,0.0000,9.9900]) cube([16.0000,8.0000,0.0100]);translate([7.0000,3.1000,16.5000]) cube([2.0000,1.8000,0.0100]);}
translate([7.0000,3.1000,16.5000]) cube([2.0000,1.8000,12.0000]);
hull(){translate([7.0000,3.1000,28.4900]) cube([2.0000,1.8000,0.0100]);translate([0.0000,0.0000,34.9900]) cube([16.0000,8.0000,0.0100]);}
translate([0.0000,0.0000,35.0000]) cube([16.0000,8.0000,10.0000]);
}
translate([8.000,-1,5.000]) rotate([-90,0,0]) linear_extrude(height=10) union(){circle(d=4.3000, $fn=48); rotate(225.000) square([2.1500,2.1500]);}
translate([8.000,-1,40.000]) rotate([-90,0,0]) linear_extrude(height=10) union(){circle(d=4.3000, $fn=48); rotate(225.000) square([2.1500,2.1500]);}
}
difference(){
union(){
translate([22.0000,0.0000,0.0000]) cube([16.0000,8.0000,10.0000]);
hull(){translate([22.0000,0.0000,9.9900]) cube([16.0000,8.0000,0.0100]);translate([29.0000,3.1000,16.5000]) cube([2.0000,1.8000,0.0100]);}
translate([29.0000,3.1000,16.5000]) cube([2.0000,1.8000,12.0000]);
hull(){translate([29.0000,3.1000,28.4900]) cube([2.0000,1.8000,0.0100]);translate([22.0000,0.0000,34.9900]) cube([16.0000,8.0000,0.0100]);}
translate([22.0000,0.0000,35.0000]) cube([16.0000,8.0000,10.0000]);
}
translate([30.000,-1,5.000]) rotate([-90,0,0]) linear_extrude(height=10) union(){circle(d=4.3000, $fn=48); rotate(225.000) square([2.1500,2.1500]);}
translate([30.000,-1,40.000]) rotate([-90,0,0]) linear_extrude(height=10) union(){circle(d=4.3000, $fn=48); rotate(225.000) square([2.1500,2.1500]);}
}
difference(){
union(){
translate([44.0000,0.0000,0.0000]) cube([16.0000,8.0000,10.0000]);
hull(){translate([44.0000,0.0000,9.9900]) cube([16.0000,8.0000,0.0100]);translate([51.0000,3.1000,16.5000]) cube([2.0000,1.8000,0.0100]);}
translate([51.0000,3.1000,16.5000]) cube([2.0000,1.8000,12.0000]);
hull(){translate([51.0000,3.1000,28.4900]) cube([2.0000,1.8000,0.0100]);translate([44.0000,0.0000,34.9900]) cube([16.0000,8.0000,0.0100]);}
translate([44.0000,0.0000,35.0000]) cube([16.0000,8.0000,10.0000]);
}
translate([52.000,-1,5.000]) rotate([-90,0,0]) linear_extrude(height=10) union(){circle(d=4.3000, $fn=48); rotate(225.000) square([2.1500,2.1500]);}
translate([52.000,-1,40.000]) rotate([-90,0,0]) linear_extrude(height=10) union(){circle(d=4.3000, $fn=48); rotate(225.000) square([2.1500,2.1500]);}
}
