// Toccata stage-0 C13a - USB-C 몰드 게이지 (12.5 × 7.6 × 25) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
translate([0.0000,0.0000,0.0000]) cube([20.5000,15.6000,25.0000]);
translate([4.0000,4.0000,-1.0000]) cube([12.5000,7.6000,27.0000]);
translate([10.2500,2.0000,24.4000]) rotate([0,0,0.00]) linear_extrude(height=0.8000) text("12.5x7.6", size=2.200, font="Liberation Sans:style=Bold", halign="center", valign="center");
}
