// Toccata stage-0 C14a - 추 컵 (DW·스프링·캡스턴 토크) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
union(){
translate([0.0000,0.0000,0.0000]) cylinder(h=18.0000, d=26.0000, $fn=64);
translate([-6.0000,-6.0000,0.0000]) cube([12.0000,12.0000,1.0000]);
translate([-15.5000,-2.0000,0.0000]) cube([4.5000,4.0000,18.0000]);
translate([11.0000,-2.0000,0.0000]) cube([4.5000,4.0000,18.0000]);
}
translate([0.0000,0.0000,1.2000]) cylinder(h=17.8000, d=23.6000, $fn=64);
translate([-13.6000,0.0000,-1.0000]) cylinder(h=20.0000, d=1.8000, $fn=64);
translate([13.6000,0.0000,-1.0000]) cylinder(h=20.0000, d=1.8000, $fn=64);
}
