// Toccata stage-0 C16b - 강철 누름 받침 (옆벽을 받치고 가운데 9.6 홈으로 강철이 내려감) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
translate([-20.0000,146.0000,0.0000]) cube([40.0000,46.0000,8.0000]);
translate([-4.8000,145.0000,-1.0000]) cube([9.6000,48.0000,10.0000]);
translate([-12.0000,169.0000,7.4000]) rotate([0,0,90.00]) linear_extrude(height=0.8000) text("C16b", size=3.500, font="Liberation Sans:style=Bold", halign="center", valign="center");
}
