// Toccata stage-0 C17a - 정하중 받침 빗 (핀 선 4줄 + 뒷벽, 레일 밑은 빔) (generated by make_stage0.py; print orientation, z = build direction)
$fn = 64;
difference(){
union(){
translate([0.0000,209.0000,0.0000]) cube([164.5000,3.0000,3.0000]);
translate([0.0000,0.0000,0.0000]) cube([3.0000,209.0100,3.0000]);
translate([40.1600,0.0000,0.0000]) cube([3.0000,209.0100,3.0000]);
translate([122.4250,0.0000,0.0000]) cube([3.0000,209.0100,3.0000]);
translate([161.5000,0.0000,0.0000]) cube([3.0000,209.0100,3.0000]);
}
translate([41.6600,12.0000,2.6000]) rotate([0,0,90.00]) linear_extrude(height=0.6000) text("C17a", size=2.000, font="Liberation Sans:style=Bold", halign="center", valign="center");
}
